function H = generate_desired_pose(x,y,z,psi,phi)
    d = [x,y,z]';
    theta1 = atan2(y,x);
    R_z_theta = [cos(theta1), -sin(theta1)  , 0;...
                 sin(theta1), cos(theta1)   ,  0;...
                 0          , 0             ,  1];
    R_z_90 =  [cos(pi/2)    , -sin(pi/2)   , 0;...
               sin(pi/2)    , cos(pi/2)    , 0;...
               0            , 0             , 1];
    R_y_90  = [cos(pi/2)    , 0             , sin(pi/2);...
               0            , 1             , 0;...
               -sin(pi/2)   , 0             ,  cos(pi/2)];
    R_x_psi = [1            , 0             , 0;...
               0            , cos(psi), -sin(psi);...
               0            , sin(psi),  cos(psi)];
    R_z_phi = [cos(phi)     , -sin(phi)     , 0;...
                 sin(phi)   , cos(phi)      ,  0;...
                 0          , 0             ,  1];

    R = R_z_theta*R_y_90*R_z_90*R_x_psi*R_z_phi;

    H = [R,d;0,0,0,1];

end